(ns kanban-sim.model.cards
  (:require clojure.pprint))

(def all-cards-str "[
        {
            \"Analysis\": 10,
            \"AnalysisDone\": 10,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 1,
            \"Development\": 11,
            \"DevelopmentDone\": 11,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S1\",
            \"StoryId\": 101,
            \"StoryOrder\": 1,
            \"Test\": 11,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"test\"
        },
        {
            \"Analysis\": 12,
            \"AnalysisDone\": 12,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 1,
            \"Development\": 13,
            \"DevelopmentDone\": 13,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S2\",
            \"StoryId\": 102,
            \"StoryOrder\": 2,
            \"Test\": 12,
            \"TestDone\": 0,
            \"Value\": 12,
            \"stage\": \"test\"
        },
        {
            \"Analysis\": 11,
            \"AnalysisDone\": 11,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 1,
            \"Development\": 12,
            \"DevelopmentDone\": 12,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S3\",
            \"StoryId\": 103,
            \"StoryOrder\": 3,
            \"Test\": 11,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"test\"
        },
        {
            \"Analysis\": 8,
            \"AnalysisDone\": 8,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 2,
            \"Development\": 11,
            \"DevelopmentDone\": 11,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S4\",
            \"StoryId\": 104,
            \"StoryOrder\": 1,
            \"Test\": 11,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"development-done\"
        },
        {
            \"Analysis\": 12,
            \"AnalysisDone\": 12,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 2,
            \"Development\": 14,
            \"DevelopmentDone\": 14,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S5\",
            \"StoryId\": 105,
            \"StoryOrder\": 2,
            \"Test\": 13,
            \"TestDone\": 0,
            \"Value\": 13,
            \"stage\": \"development-done\"
        },
        {
            \"Analysis\": 9,
            \"AnalysisDone\": 9,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 3,
            \"Development\": 11,
            \"DevelopmentDone\": 3,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S6\",
            \"StoryId\": 106,
            \"StoryOrder\": 1,
            \"Test\": 3,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"development\"
        },
        {
            \"Analysis\": 10,
            \"AnalysisDone\": 10,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 3,
            \"Development\": 13,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S7\",
            \"StoryId\": 107,
            \"StoryOrder\": 2,
            \"Test\": 14,
            \"TestDone\": 0,
            \"Value\": 12,
            \"stage\": \"development\"
        },
        {
            \"Analysis\": 8,
            \"AnalysisDone\": 8,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 3,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S8\",
            \"StoryId\": 108,
            \"StoryOrder\": 1,
            \"Test\": 14,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"analysis-done\"
        },
        {
            \"Analysis\": 9,
            \"AnalysisDone\": 3,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 4,
            \"Development\": 13,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S9\",
            \"StoryId\": 109,
            \"StoryOrder\": 1,
            \"Test\": 15,
            \"TestDone\": 0,
            \"Value\": 12,
            \"stage\": \"analysis\"
        },
        {
            \"Analysis\": 10,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 4,
            \"Development\": 10,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S10\",
            \"StoryId\": 110,
            \"StoryOrder\": 2,
            \"Test\": 12,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"analysis\"
        },
        {
            \"Analysis\": 12,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 5,
            \"Development\": 11,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S11\",
            \"StoryId\": 111,
            \"StoryOrder\": 1,
            \"Test\": 15,
            \"TestDone\": 0,
            \"Value\": 13,
            \"stage\": \"ready\"
        },
        {
            \"Analysis\": 7,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 6,
            \"Development\": 10,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S12\",
            \"StoryId\": 112,
            \"StoryOrder\": 2,
            \"Test\": 13,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"ready\"
        },
        {
            \"Analysis\": 8,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 6,
            \"Development\": 11,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S13\",
            \"StoryId\": 113,
            \"StoryOrder\": 3,
            \"Test\": 12,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"ready\"
        },
        {
            \"Analysis\": 7,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 7,
            \"Development\": 11,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S14\",
            \"StoryId\": 114,
            \"StoryOrder\": 4,
            \"Test\": 11,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"ready\"
        },
        {
            \"Analysis\": 5,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S15\",
            \"StoryId\": 115,
            \"StoryOrder\": 1,
            \"Test\": 8,
            \"TestDone\": 0,
            \"Value\": 7,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 5,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 7,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S16\",
            \"StoryId\": 116,
            \"StoryOrder\": 2,
            \"Test\": 6,
            \"TestDone\": 0,
            \"Value\": 6,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 5,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 8,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S17\",
            \"StoryId\": 117,
            \"StoryOrder\": 3,
            \"Test\": 7,
            \"TestDone\": 0,
            \"Value\": 7,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 4,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S18\",
            \"StoryId\": 118,
            \"StoryOrder\": 4,
            \"Test\": 8,
            \"TestDone\": 0,
            \"Value\": 7,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 9,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S19\",
            \"StoryId\": 119,
            \"StoryOrder\": 5,
            \"Test\": 8,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 8,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 12,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S20\",
            \"StoryId\": 120,
            \"StoryOrder\": 6,
            \"Test\": 7,
            \"TestDone\": 0,
            \"Value\": 8,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 7,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S21\",
            \"StoryId\": 121,
            \"StoryOrder\": 7,
            \"Test\": 7,
            \"TestDone\": 0,
            \"Value\": 7,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 9,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 11,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S22\",
            \"StoryId\": 122,
            \"StoryOrder\": 8,
            \"Test\": 8,
            \"TestDone\": 0,
            \"Value\": 9,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 7,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 10,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S23\",
            \"StoryId\": 123,
            \"StoryOrder\": 9,
            \"Test\": 9,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 8,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 10,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S24\",
            \"StoryId\": 124,
            \"StoryOrder\": 10,
            \"Test\": 9,
            \"TestDone\": 0,
            \"Value\": 9,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 10,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 8,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S25\",
            \"StoryId\": 125,
            \"StoryOrder\": 11,
            \"Test\": 7,
            \"TestDone\": 0,
            \"Value\": 8,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 8,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 11,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S26\",
            \"StoryId\": 126,
            \"StoryOrder\": 12,
            \"Test\": 13,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 10,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 11,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S27\",
            \"StoryId\": 127,
            \"StoryOrder\": 13,
            \"Test\": 12,
            \"TestDone\": 0,
            \"Value\": 10,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 9,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S28\",
            \"StoryId\": 128,
            \"StoryOrder\": 14,
            \"Test\": 9,
            \"TestDone\": 0,
            \"Value\": 9,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 11,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 10,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S29\",
            \"StoryId\": 129,
            \"StoryOrder\": 15,
            \"Test\": 11,
            \"TestDone\": 0,
            \"Value\": 11,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 9,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 8,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"S30\",
            \"StoryId\": 130,
            \"StoryOrder\": 16,
            \"Test\": 7,
            \"TestDone\": 0,
            \"Value\": 7,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 14,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 15,
            \"DevelopmentDone\": 0,
            \"DueDay\": 21,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"E1\",
            \"StoryId\": 501,
            \"StoryOrder\": 32,
            \"Test\": 15,
            \"TestDone\": 0,
            \"Value\": 5000,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 4,
            \"AnalysisDone\": 4,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 3,
            \"Development\": 5,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": \"Database Upgrade\",
            \"Name\": \"I1\",
            \"StoryId\": 601,
            \"StoryOrder\": 3,
            \"Test\": 11,
            \"TestDone\": 0,
            \"Value\": 0,
            \"stage\": \"development\"
        },
        {
            \"Analysis\": 1,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 8,
            \"Development\": 13,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": \"Document Legacy Code\",
            \"Name\": \"I2\",
            \"StoryId\": 602,
            \"StoryOrder\": 5,
            \"Test\": 6,
            \"TestDone\": 0,
            \"Value\": 0,
            \"stage\": \"ready\"
        },
        {
            \"Analysis\": 1,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 6,
            \"DevelopmentDone\": 0,
            \"DueDay\": 0,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": \"Refactor core subsystem\",
            \"Name\": \"I3\",
            \"StoryId\": 603,
            \"StoryOrder\": 3,
            \"Test\": 1,
            \"TestDone\": 0,
            \"Value\": 0,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 3,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 5,
            \"DevelopmentDone\": 0,
            \"DueDay\": 15,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"F1\",
            \"StoryId\": 701,
            \"StoryOrder\": 1,
            \"Test\": 7,
            \"TestDone\": 0,
            \"Value\": -2200,
            \"stage\": \"deck\"
        },
        {
            \"Analysis\": 4,
            \"AnalysisDone\": 0,
            \"Blocked\": 0,
            \"BlockedDone\": 0,
            \"BlockedLabel\": null,
            \"DayDeployed\": 0,
            \"DayReady\": 0,
            \"Development\": 9,
            \"DevelopmentDone\": 0,
            \"DueDay\": 20,
            \"Expedited\": false,
            \"IsBlocked\": false,
            \"Label\": null,
            \"Name\": \"F2\",
            \"StoryId\": 702,
            \"StoryOrder\": 2,
            \"Test\": 8,
            \"TestDone\": 0,
            \"Value\": 2500,
            \"stage\": \"deck\"
        }
    ]")

(def all-cards-js (.parse js/JSON all-cards-str))
(def all-cards (js->clj all-cards-js :keywordize-keys true))

(defn cards->map [cards]
  (reduce #(if (:StoryId %2)
             (assoc %1 (:StoryId %2) %2)
             (throw (js/Error. (str "cards->map: no StoryId in card: " %2)))) {} cards))

(first all-cards)

;; make a map with StoryId as the key and the card as value
(def indexed-cards (reduce #(assoc %1 (:StoryId %2) %2) {} all-cards))
indexed-cards


;; TODO add done cards
(defn filter-stage [all-values stage] (filter #(= (:stage %) stage) all-values))

(filter-stage all-cards "test")

(clojure.pprint/pp)

(comment
  (type all-cards)
  (def cards all-cards)
  (type cards)
  (def test-cards (filter #(= (:stage %) "test") cards))
  (def rest-cards (filter #(not= (:stage %) "test") cards))
  (type test-cards)
  (into (into [] rest-cards) test-cards)
  ;
  )


